name: Documentation

on:
  release:
    types: [published]

jobs:
  test:
    name: Generate and Publish documentation
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Install Jazzy
      run: sudo gem install jazzy
    - name: Generate documentation
      run: jazzy
    - name: Publish documentation
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        publish_dir: ./docs
        github_token: ${{ secrets.GITHUB_TOKEN }}
